---
swagger: "2.0"
info:
  description: "Esta versão administra a movimentação de sondas espaciais para soluç\
    ão do desafio da credere."
  version: "1.0.0"
  title: "Desafio Credere API"
  contact:
    name: "Robson Arruda"
    email: "robson.arruda@outlook.com"
host: "localhost:3000"
basePath: "/v1"
tags:
- name: "V1"
schemes:
- "http"
- "https"
paths:
  /v1/probe:
    post:
      tags:
      - "V1"
      summary: "Cria uma sonda"
      description: "Cria uma sonda com posição padrão"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              xAxis:
                type: "integer"
                example: 0
              yAxix:
                type: "integer"
                example: 0
              face:
                type: "string"
                example: "D"
        500:
          description: "Erro interno no servidor"
  /v1/probe/{id}/position:
    get:
      tags:
      - "V1"
      summary: "Exibe a posição da sonda"
      description: "Exibe a posição em que a sonda está"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              xAxis:
                type: "integer"
                example: 0
              yAxix:
                type: "integer"
                example: 0
        400:
          description: "Requisição inválida"
        404:
          description: "Sonda não encontrada"
        500:
          description: "Erro interno no servidor"
  /v1/probe/{id}/move:
    put:
      tags:
      - "V1"
      summary: "Move a sonda"
      description: "Executa comandos para movimentar a sonda"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              xAxis:
                type: "integer"
                example: 0
              yAxix:
                type: "integer"
                example: 0
              face:
                type: "string"
                example: "D"
        400:
          description: "Requisição inválida"
        404:
          description: "Sonda não encontrada"
        500:
          description: "Erro interno no servidor"
  /v1/probe/{id}/position/reset:
    put:
      tags:
      - "V1"
      summary: "Retorna sonda para posição inicial"
      description: "Retorna a sonda para o ponto inicial xAxis = 0, yAxis = 0 e face\
        \ = D"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
      responses:
        204:
          description: "No content"
        404:
          description: "Sonda não encontrada"
        500:
          description: "Erro interno no servidor"
definitions:
  Probe:
    properties:
      id:
        type: "integer"
        format: "int"
        example: 1
      xAxis:
        type: "integer"
        format: "int"
        example: 0
      yAxis:
        type: "integer"
        format: "int"
        example: 0
      face:
        type: "string"
        format: "char1"
        example: "D"
      created_at:
        type: "string"
        format: "timestamp"
        example: ""
      updated_at:
        type: "string"
        format: "timestamp"
        example: ""
  inline_response_200:
    properties:
      xAxis:
        type: "integer"
        example: 0
      yAxix:
        type: "integer"
        example: 0
      face:
        type: "string"
        example: "D"
    example:
      face: "D"
      xAxis: 0
      yAxix: 0
  inline_response_200_1:
    properties:
      xAxis:
        type: "integer"
        example: 0
      yAxix:
        type: "integer"
        example: 0
    example:
      xAxis: 0
      yAxix: 0
