version: '2'
 
services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
 
  api:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    command: 
      rails server -b 0.0.0.0
 
volumes:
  postgres: